-- 1
SELECT 
	p.ID_PESSOA,
	p.NOME,
	c.TIPO,
	c.NUMERO,
	c.DESCRICAO
FROM 
	VEM_SER.PESSOA p
RIGHT JOIN VEM_SER.CONTATO c 
ON (p.ID_PESSOA = c.ID_PESSOA);

-- 2
SELECT 
	p.ID_PESSOA,
	p.NOME,
	ep.ID_ENDERECO,
	ep.TIPO,
	ep.LOGRADOURO,
	ep.NUMERO,
	ep.COMPLEMENTO,
	ep.CEP,
	ep.CIDADE,
	ep.ESTADO 
FROM ((VEM_SER.PESSOA p
RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON	(p.ID_PESSOA = pxpe.ID_PESSOA))
RIGHT JOIN VEM_SER.ENDERECO_PESSOA ep ON ep.ID_ENDERECO = pxpe.ID_ENDERECO);

-- 4
SELECT 
	p.ID_PESSOA,
	p.NOME,
	c.TIPO,
	c.NUMERO,
	c.DESCRICAO
FROM 
	VEM_SER.PESSOA p
FULL OUTER JOIN VEM_SER.CONTATO c 
ON (p.ID_PESSOA = c.ID_PESSOA);

-- 5
SELECT 
	p.ID_PESSOA,
	p.NOME,
	ep.ID_ENDERECO,
	ep.TIPO,
	ep.LOGRADOURO,
	ep.NUMERO,
	ep.COMPLEMENTO,
	ep.CEP,
	ep.CIDADE,
	ep.ESTADO 
FROM ((VEM_SER.PESSOA p
FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON	(p.ID_PESSOA = pxpe.ID_PESSOA))
FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA ep ON ep.ID_ENDERECO = pxpe.ID_ENDERECO);

-- 7
SELECT 
	* 
FROM VEM_SER.PESSOA p 
WHERE EXISTS 
	(SELECT 
		pxpe.ID_PESSOA 
	FROM 
		VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe 
	WHERE pxpe.ID_PESSOA = p.ID_PESSOA);

-- 8
SELECT
	p.ID_PESSOA,
	p.NOME 
FROM VEM_SER.PESSOA p
UNION
SELECT
	ep.ID_ENDERECO, 
	ep.LOGRADOURO  
FROM VEM_SER.ENDERECO_PESSOA ep;
