--- HOMEWORK 1
--- Criar uma tabela ESTUDANTE com os campos:
--- id: numérico e chave primária
--- nome: texto até 200 caracteres não nulo
--- data_nascimento: Data não nulo
--- nr_matricula: numérico de 10 não nulo, único (UK)
--- ativo: caracter (‘S’ = ativo, ‘N’ = não ativo)

CREATE TABLE VEM_SER.ESTUDANTE (
	id NUMBER NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo CHAR(1) NOT NULL,
	PRIMARY KEY(id_pessoa)
);

-- Criar uma sequence para essa tabela (seq_estudante);
CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

-- Inserir 10 registros para essa tabela;
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Matheus Goncalves', TO_DATE('10-02-1991', 'dd-mm-yyyy'), 20220001, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Andrés DAlessandro', TO_DATE('15-04-1981', 'dd-mm-yyyy'), 20220002, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Celso Roth', TO_DATE('30-11-1957', 'dd-mm-yyyy'), 20220003, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Clemer Silva', TO_DATE('20-10-1968', 'dd-mm-yyyy'), 20220004, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Alan Patrick', TO_DATE('13-05-1991', 'dd-mm-yyyy'), 20220005, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Alex Raphael', TO_DATE('25-03-1982', 'dd-mm-yyyy'), 20220006, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Abel Braga', TO_DATE('01-09-1952', 'dd-mm-yyyy'), 20220007, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Pablo Guiñazú', TO_DATE('26-08-1978', 'dd-mm-yyyy'), 20220008, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Víctor Cuesta', TO_DATE('19-10-1988', 'dd-mm-yyyy'), 20220009, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.SEQ_ESTUDANTE.nextval, 'Paulo Roberto Falcão', TO_DATE('16-10-1953', 'dd-mm-yyyy'), 20220010, 'S');

-- Selecionar os registros;
SELECT * FROM VEM_SER.ESTUDANTE;
